feat: initial fusionauth swift SDK for iOS with workspace and sample quickstart (#6)
* feat: first prototype for login with ObservableObject

* style: swift lint

* refactor: move getUserInfo implementation to method

* feat: add logout

* refactor: remove print

* style: update swiftlint.yml

* refactor: various code improvements

- Don't require view to be provided when calling authorize / logout
- Logging
- use Dispatch.mein.async instead of @MainActor
- use @discardableResult

* test: set up tests

* refactor(package.swift): add macos version

- the build process requires a higher macos version according to the error in the autobuild 

error: the library 'FusionAuth' requires macos 10.13, but depends on the product 'SwiftLintBuildToolPlugin' which requires macos 12.0; consider changing the library 'FusionAuth' to require macos 12.0 or later, or the product 'SwiftLintBuildToolPlugin' to require macos 10.13 or earlier.

* build(deps): update multiple dependencies
- Fix all versions to exact
- Add swift-docc-plugin
- Bump SwiftLint

* refactor(workspace): add FusionAuthSDK workspace with FusionAuth scheme from package

* ci(codeql): switch setup-xcode action to mxcl/xcodebuild

- https://github.com/mxcl/xcodebuild

(cherry picked from commit 3ac5cefbe9942a4f98b66d391ef449ea57b96311)

* refactor(workspace): add and link TestApp in to FusionAuthSDK workspace
- add fusionauth-ios-mobilesdk-test-app as a submodule https://github.blog/open-source/git/working-with-submodules/
- add Quickstart TestApp to FusionAuthSDK workspace

* feat: enable (theoretical) macos support

* docs: test documentation from SourceDocs

* refactor(workspace): Remove submodule

* refactor(workspace): Add Quickstart in to Samples

* fix(OAuthAuthorizationService): correct linting error

* build(deps): bump fusionauth to 1.52.1

* refactor(workspace): rename quickstart app, add package dependencies differently

* refactor(workspace): rename quickstart app, add package dependencies differently

* ci(codeql): split in to multiple codeql workflows
- split quickstart in to own workflow
- add working directory defaults pointing to quickstart

* ci(codeql): add package workflow

* ci(codeql): add default working-directory

* ci(codeql): try with setup-xcode

* ci(codeql): try with limiting paths

* ci(codeql): add specific codeql-config

* refactor(workspace): change to relative path

* ci(codeql): update build modes and fix analysis

* ci(codeql): remove push and pull path filter

* ci(codeql): update action version and add manual build

* ci(codeql): switch to autobuild

* ci(codeql): switch codeql-package to manual build

* ci(codeql): switch codeql-samples-quickstart to manual build

* docs: add SourceDocs script

* ci(codeql): add destination matrix to samples-quickstart

* refactor(codeql): add swiftlint

* refactor(codeql): skipPackagePluginValidation

- https://forums.swift.org/t/some-build-plug-ins-are-disabled-because-they-have-changed-or-have-never-been-enabled-enable-them-now/61075

* refactor(codeql): check disk space usage

* refactor(codeql): check disk space usage with sleep

* refactor(codeql): remove old xcode versions

* refactor(codeql): only check what can be removed

* refactor(codeql): check for old xcode and remove all except the latest

* refactor(codeql): specify xcode version to be installed and kept

* refactor(codeql): additional messaging and disk space check before build

* build(deps): bump codeql to 3.26.6

* build(deps): bump SwiftLint and Swift Docc Plugin

* build(deps): bump quickstart TestApp dependencies

* refactor(gitignore): update exclustions

* ci(codeql): matrix with older xcode and platform

* ci(codeql): update matrix

* build(deps): bump setup-python to 5.2.0

* refactor(fusionauth): add and correct docker-compose configurations

* ci(codeql): execute analysis if build successful or not

* ci(codeql): build with build-tests, debug and verbose

* build(deps): bump Package.resolved

* fix: error with closure

* fix: error with closure

* feat: prototyping TokenManager

* ci(workflows): update timings and naming

* build(deps): bump fusionauth to 1.53.2

* fix: error with closure

reveting and instead enclosing them as a string to avoid build error
a04a36ab48ee86209cec3987d5347c093717838f
72a495644e3df13e9331205c29d5ccd9042fe1de

otherwise its crashing at Thread 8: Fatal error: Unexpectedly found nil while unwrapping an Optional value

* build(deps): bump swiftlint and swift-docc-plugin

* fix: redirectUri bundleIdentifier usage

* refactor: make composition variables internal

* build(deps): bump swift to 6.0.0 and xcode to 16.0

* build(deps): refactor swift to 6.0

* build(deps): downgrade swift to 5.10.1
- swift-actions/setup-swift does not yet support swift 6.0 https://github.com/swift-actions/setup-swift/pull/684 https://github.com/swift-actions/setup-swift/issues/683

* build(deps): downgrade xcode to 15.4 because swift 6.0.0 is not yet available

* refactor(documentation): generate newest version

* docs: add class descriptions

* docs: generate newest version

* docs: add func descriptions

* docs: generate newest version

* docs: generate docc version

* docs: remove docc version

* docs: remove all "Returns: Void"

* docs: generate latest sourcedocs version

* docs(README): add Getting Started, Usage and Dev Tooling draft.

* test(swift): add unit tests for AuthorizationManager, TokenManager and UserInfo

* test(swift): update AuthorizationManager

* test(swift): lint fixes

* docs: add period at the end of sentences

* docs: create github default community health files

- according to https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file

* refactor(AuthorizationManager): allow storage to be optional

* docs: update README adding more TODOs

* ci(e2e-test): add initial ios-matrix workflow

* ci(workflows): add fixed runner to macos-14

* ci(workflows): downgrade to xcode 16.0

* ci(workflows): downgrade to xcode 15.4 and fix swift to 5.10.1

* ci(workflows): downgrade swift-tools-version minimum to 5.8

* build(deps): downgrade PinsStorage to version 2

* build(deps): remove version binding from SwiftLint

* build(deps): downgrade version SwiftLint to 0.56.0

* build(deps): downgrade version SwiftLint to 0.54.0

* build(deps): downgrade version SwiftLint to 0.53.0

* feat: implement TokenManager, Refresh Token

* build(deps): split swift package in to post and pre swift 5.10

* build(deps): use SwiftLintPlugin pre swift 5.10

* ci(e2e-test): add iOS 15.5

* feat: use userInfo email or name if given_ or family_name is not available

* refactor: rename TestApp to Quickstart

* docs(CONTRIBUTING): add swiftformat

* ci(e2e-test): add simulator runtime installation

* test: base UI test login to logout

* ci(e2e-test): simulator runtime installation with xcodes

* refactor: remove docs script

* refactor: downgrade IPHONEOS_DEPLOYMENT_TARGET to 15.0

* ci(e2e-test): simulator device for iOS 15.5 set to iPhone 13

* ci(e2e-test): simulator installation test

* refactor(workspace): downgrade objectVersion to 55

* ci(e2e-test): downgrade iOS to 18.0

* refactor(workspace): convert QuickstartTests from folder to group to solve xcode compatability issue

* ci(e2e-test): adjust versions

* ci(e2e-test): install simulator for macos-13

---------

Co-authored-by: Colin Frick <colin+github@sonderformat.llc>