refactor(package.swift): add macos version
- the build process requires a higher macos version according to the error in the autobuild 

error: the library 'FusionAuth' requires macos 10.13, but depends on the product 'SwiftLintBuildToolPlugin' which requires macos 12.0; consider changing the library 'FusionAuth' to require macos 12.0 or later, or the product 'SwiftLintBuildToolPlugin' to require macos 10.13 or earlier.